{
    'input_power': Result(value=0, unit='W'),
    'line_voltage_A_B': Result(value=0.0, unit='V'),
    'line_voltage_B_C': Result(value=0.0, unit='V'),
    'line_voltage_C_A': Result(value=0.0, unit='V'),
    'phase_A_voltage': Result(value=0.0, unit='V'),
    'phase_B_voltage': Result(value=0.0, unit='V'),
    'phase_C_voltage': Result(value=0.0, unit='V'),
    'phase_A_current': Result(value=0.0, unit='A'),
    'phase_B_current': Result(value=0.0, unit='A'),
    'phase_C_current': Result(value=0.0, unit='A'),
    'day_active_power_peak': Result(value=0, unit='W'),
    'active_power': Result(value=0, unit='W'),
    'reactive_power': Result(value=0, unit='VA'),
    'power_factor': Result(value=0.0, unit=None),
    'grid_frequency': Result(value=0.0, unit='Hz'),
    'efficiency': Result(value=0.0, unit='%'),
    'internal_temperature': Result(value=0.0, unit='°C'),
    'insulation_resistance': Result(value=None, unit='MOhm'),
    'device_status': Result(value='Standby: no irradiation', unit=None),
    'fault_code': Result(value=0, unit=None),
    'startup_time': Result(value=None, unit=None),
    'shutdown_time': Result(value=None, unit=None),
    'accumulated_yield_energy': Result(value=0.0, unit='kWh'),
    'daily_yield_energy': Result(value=0.0, unit='kWh'),
    'state_1': Result(value=['Standby'], unit=None),
    'state_2': Result(value=['Locked', 'PV disconnected', 'No DSP data collection'], unit=None),
    'state_3': Result(value=['On-grid', 'Off-grid switch disabled'], unit=None),
    'alarm_1': Result(value=[], unit=None),
    'alarm_2': Result(value=[], unit=None),
    'alarm_3': Result(value=[], unit=None),
    'pv_01_voltage': Result(value=0.0, unit='V'),
    'pv_01_current': Result(value=0.0, unit='A'),
    'pv_02_voltage': Result(value=0.0, unit='V'),
    'pv_02_current': Result(value=0.0, unit='A')
}
